
version: 2.1

#orbs:

  #node: circleci/node@5.0.2

jobs:
  
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: npm audit            

workflows:
  sampleCI:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires: 
           - test
